In [62]:
import tensorflow as tf

vector_tensor = tf.constant([1, 2, 3, 4])
first_element = vector_tensor[0]
matrix_tensor = tf.constant([[1, 2, 3], [3, 4, 5], [8, 9, 10]])

matrix_slice = matrix_tensor[0:, 0:]

In [63]:
print("vector_tensor")
print(vector_tensor.numpy())

print("\nfirst_element")
print(first_element.numpy())

print("\nmatrix_tensor")
print(matrix_tensor.numpy())

print("\nmatrix_slice")
print(matrix_slice.numpy())

vector_tensor
[1 2 3 4]

first_element
1

matrix_tensor
[[ 1  2  3]
 [ 3  4  5]
 [ 8  9 10]]

matrix_slice
[[ 1  2  3]
 [ 3  4  5]
 [ 8  9 10]]
